## Global configuration

server:
    port: 8761

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
    server:
        enable-self-preservation: true
#        eviction-interval-timer-in-ms: 1
#        wait-time-in-ms-when-sync-empty: 1
    instance:
        lease-expiration-duration-in-seconds: 0

spring:
    application:
        name: eureka-server
    datasource:
        url: jdbc:postgresql://localhost:5432/learn_database
        username: links
        password: links
#        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        open-in-view: true

logging:
    level:
        org:
            springframework:
                security: trace
