spring:
    application:
        name: sourcing-service
    datasource:
        url: jdbc:postgresql://localhost:5432/learn_database
        username: links
        password: links
    #        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        open-in-view: true

server:
    #    port: 8081
    port: 0  # Cela permet de démarrer plusieurs instances avec des ports aléatoires

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
    level:
        org:
            springframework:
                security: trace
