package io.learn.user.entity;

public enum Role {
    ADMIN_SUDO,
    ADMIN, DEVELOPER, SECURITY_MANAGER,
    ADMIN_SUDO_POOLS, MANAGER_USERS, MANAGER_TRANSACTIONS, MANAGER_COMMANDS,
    ADMIN_POOLS,
    SERVICE_CLIENT, ORDER_MANAGER, BUSINESS_NEEDS_ANALYST,
    USER_STANDARD, USER_PARTNER
}
